version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    registries: '*'
    ignore:
      # update-package-lock workflow already handles minor/patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
